### PR TITLE
Improve cli styling

### PR DESCRIPTION
**Pull request by Dgaduin**
#4

### CODE REVIEW

**Comment by NotMyself** [comment]
TODO:

- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by NotMyself** [comment]
@Dgaduin I cannot tell from your screenshot if you are on Windows or a unix-y OS. Do you have a way to test on windows?

**Comment by Dgaduin** [comment]
It was Windows, with the Windows Terminal and I'm attaching a screenshot from the cmd. 
image

**Comment by NotMyself** [comment]
Perfect thank you!

@all-contributors please add @Dgaduin for code

**Pull request merged**
