### PR TITLE
Switch from Appveyor to GitHub Actions

### PR DESCRIPTION
**Pull request by MaxAtoms**
The latest Appveyor build is four years old. It does not seem to be running for newer commits.
This pull request will switch the repo from Appveyor to GitHub Actions.
One benefit compared to the current CI process is that the action will run tests for pull requests as well.

### CODE REVIEW

**Comment by MaxAtoms** [comment]
I'd like to hear your thoughts on this change, @NotMyself .
If you agree to switch to GitHub Actions, I will have a look over this pull request and tell you once it is ready for review.

**Comment by NotMyself** [comment]
@MaxAtoms This is a good idea. Actions were not a thing when we first implemented the CI.

**Comment by MaxAtoms** [comment]
Hey, @NotMyself 👋🏽 I updated the action to use .NET 6, so this PR is now ready again to be merged. You can see the action in action (😉) on my fork: https://github.com/MaxAtoms/DotNetCoreKoans/actions. Also note that I updated the README to include a corresponding badge.
If you decide to merge this, I'd highly appreciate a `hacktoberfest-accepted` label on this PR as well as on #165.

**Comment by NotMyself** [comment]
Done and done!

**Pull request merged**
